### ISSUE TITLE
ImportError: cannot import name 'MAXFD'

### ISSUE THREAD

**Issue by hroncok** [rfk/playitagainsam#16]
```
$ pias record foo.json
Traceback (most recent call last):
  File "/home/churchyard/.local/bin/pias", line 5, in <module>
    import playitagainsam
  File "/home/churchyard/.local/lib/python3.5/site-packages/playitagainsam/__init__.py", line 153, in <module>
    from playitagainsam.recorder import Recorder, join_recorder
  File "/home/churchyard/.local/lib/python3.5/site-packages/playitagainsam/recorder.py", line 18, in <module>
    from playitagainsam.util import forkexec_pty, get_default_shell
  File "/home/churchyard/.local/lib/python3.5/site-packages/playitagainsam/util.py", line 23, in <module>
    from subprocess import MAXFD
ImportError: cannot import name 'MAXFD'
```

**Comment by hroncok** [comment]
Easy to solve:

```patch
diff --git a/playitagainsam/util.py b/playitagainsam/util.py
index 3bc6a90..b53babb 100644
--- a/playitagainsam/util.py
+++ b/playitagainsam/util.py
@@ -20,7 +20,16 @@ try:
 except ImportError:
     psutil = None
 
-from subprocess import MAXFD
+try:
+    from subprocess import MAXFD
+except ImportError:
+    # On Python 3 this is no longer there
+    # This is how it was done
+    try:
+        MAXFD = os.sysconf("SC_OPEN_MAX")
+    except:
+        MAXFD = 256
+
 
 
 class _UNSPECIFIED(object):
```

But there ar emore problems on Python 3.5 later, I'm going to look at them and try to fix them.
