### ISSUE TITLE
permission denied on macOS

### ISSUE THREAD

**Issue by ishahid** [rfk/playitagainsam#19]
On macOS Sierra, I get this error when trying to run pias normally.

```
$ pias record output.txt
Traceback (most recent call last):
  File "/usr/local/bin/pias", line 6, in <module>
    res = playitagainsam.main(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/playitagainsam/__init__.py", line 179, in main
    default=util.get_default_shell(fallback=None))
  File "/usr/local/lib/python2.7/site-packages/playitagainsam/util.py", line 149, in get_default_shell
    for ancestor in get_ancestor_processes():
  File "/usr/local/lib/python2.7/site-packages/playitagainsam/util.py", line 127, in get_ancestor_processes
    _ANCESTOR_PROCESSES.append(proc.parent().exe())
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 684, in exe
    exe = self._proc.exe()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 350, in exe
    return cext.proc_exe(self.pid)
OSError: [Errno 13] Permission denied
```

I installed it from https://pypi.python.org/pypi/playitagainsam using pip.

**Comment by rfk** [comment]
Thanks for the report!  I don't have my mac with me this week (at PyCon AU) so unfortunately I can't try to reproduce to debug right now, but you may be able to work around this by passing an explicit `--shell=/path/to/wherever/Terminal.app/lives` argument to `pias`.

**Comment by ishahid** [comment]
Same error.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
