### ISSUE TITLE
AttributeError: 'module' object has no attribute 'error'

### ISSUE THREAD

**Issue by jgarber** [rfk/playitagainsam#9]
I could use your help troubleshooting an error. I'm using homebrew Python 2.7.5.

I get: 

```
/usr/local/bin/pias record foo
Traceback (most recent call last):
  File "/usr/local/bin/pias", line 5, in <module>
    pkg_resources.run_script('playitagainsam==0.2.1', 'pias')
  File "build/bdist.macosx-10.8-x86_64/egg/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "build/bdist.macosx-10.8-x86_64/egg/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/playitagainsam-0.2.1-py2.7.egg/EGG-INFO/scripts/pias", line 6, in <module>
    res = playitagainsam.main(sys.argv)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/playitagainsam-0.2.1-py2.7.egg/playitagainsam/__init__.py", line 152, in main
    default=util.get_default_shell())
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/playitagainsam-0.2.1-py2.7.egg/playitagainsam/util.py", line 128, in get_default_shell
    for ancestor in get_ancestor_processes():
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/playitagainsam-0.2.1-py2.7.egg/playitagainsam/util.py", line 108, in get_ancestor_processes
    except psutil.error.Error:
AttributeError: 'module' object has no attribute 'error'
```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
